# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewVideo',
            fields=[
                ('video_title', models.TextField(blank=True, db_index=True, null=True)),
                ('video_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('moods', models.CharField(choices=[('HAPPY', 'Happy'), ('LOVE', 'Love'), ('SAD', 'Sad'), ('CHILL', 'Chill'), ('WORKOUT', 'workout')], default='HAPPY', max_length=20)),
                ('labeled', models.NullBooleanField()),
                ('video_description', models.TextField(blank=True, null=True)),
                ('predicted_moods', models.CharField(blank=True, max_length=17, null=True)),
            ],
        ),
    ]
